apiVersion: v1
kind: Service
metadata:
  name: employee-scheduler-prod-service
spec:
  type: LoadBalancer
  loadBalancerIP: 10.48.229.48
  selector:
    app: employee-scheduler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
